### ISSUE TITLE
Theme Has Stopped Applying

### ISSUE THREAD

**Issue by ghost** [Stuyk/honkit-plugin-theme-darkening#1]
As the title says this plugin is no longer applying the dark theme on my github pages site using honkit gitbooks.
My gitbooks site still displays a complete white bg even with this loaded.

# Code

`book.json`
```json
 {
    "root": "./",
    "title": "Socket Development",
    "description": "Open Source Development Community",
    "author": "Socket Development <github.com/Socket-Development>",
    "plugins": [
        "sitemap",
        "honkit-plugin-theme-darkening"
    ],
    "pluginsConfig": {
        "sitemap": {
            "url": "https://socket-development.github.io/socket-docs/"
        }
    }
}
```

`package.json`
```json
{
  "name": "socket-development",
  "version": "1.0.0",
  "description": "Open Source Development Community!",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "serve": "honkit serve _src",
    "build": "honkit build _src",
    "reload": "honkit build --reload _src",
    "benchmark": "honkit build benchmark _src"
  },
  "keywords": [
    "development",
    "gitbook",
    "documentation",
    "open-source"
  ],
  "author": "Socket Development <github.com/Socket-Development",
  "license": "ISC",
  "devDependencies": {
    "honkit": "^3.7.4",
    "honkit-plugin-theme-darkening": "^1.0.3",
    "honkit-plugin-sitemap": "^1.0.2"
  }
}
```
`deploy.yml`
```yml
name: deploy-honkit-gitbook

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: npx honkit build _src
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_src/_book
```
